### ISSUE TITLE
Admin account ("me")

### ISSUE THREAD

**Issue by SafeWay-2022** [SafeWay-2022/safeway#12]
A user of the Admin should have possibility to view and update his personal info. 

On the upper right corner, there should be an 'account' quick-menu with the following functions:
1. me -> Get info from: https://c4u-match-org.appspot.com/docs#/Volunteers/show_user_users_get__username__get
2. Update -> Update personal info by calling: https://c4u-match-org.appspot.com/docs#/Volunteers/self_user_update_users_me__patch
3. Logout

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/13

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/16

**Comment by SafeWay-2022** [comment]
Info is empty
![image](https://user-images.githubusercontent.com/105425162/173282718-671240d0-2234-4bcf-87a1-58e0b5a1eb6d.png)

Note we have more general user info at: /users/me/
Please use it instead of: /aaa/me/

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/17

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/20
should work from https://safeway-chi.vercel.app/

**Comment by SafeWay-2022** [comment]
Works. Thanks.
