### ISSUE TITLE
Bearer token is not sent 

### ISSUE THREAD

**Issue by SafeWay-2022** [SafeWay-2022/safeway#15]
Calls to the Server should include the auth-token from the login.

**To Reproduce**
Example:
`curl 'https://safeway-chi.vercel.app/api/poi/6283e8aab1877bac4a3504f5' \
  -X 'DELETE' \
  -H 'authority: safeway-chi.vercel.app' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9,he;q=0.8' \
  -H 'origin: https://safeway-chi.vercel.app' \
  -H 'referer: https://safeway-chi.vercel.app/poi' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36' \
  --compressed`

**Expected behavior**
An Header: **authorization** with Bearer value should be sent.
like:
`authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhaGlrIiwic2NvcGVzIjpbInN1cGVydXNlciIsIm1lOlIiLCJtZTpVIiwibWU6QSJdLCJleHAiOjE2NTUwMzQ5NjN9.nfL6kDLAYlv5JDo6OaKe99rZ0HKE9qBnPeHJmajqvzY
`

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/21
