### ISSUE TITLE
Support Boolean field

### ISSUE THREAD

**Issue by ahik** [SafeWay-2022/safeway#2]
Add option to use Boolean fields in a table.

**Comment by IlyaGershman** [comment]
added [InputSwitch](https://ant.design/components/switch/)

**Comment by ahik** [comment]
@IlyaGershman 
How to set it within the config.json? 
This one doesn't work:
`
{
          "title": "Valid",
          "dataIndex": "valid",
          "width": "10%",
          "editable": true,
          "type": "switch"
},
`

**Comment by IlyaGershman** [comment]
Replace type 'switch' with type 'boolean'

**Comment by ahik** [comment]
Thanks

**Comment by ahik** [comment]
Working fine.
