### ISSUE TITLE
Nearby filtering

### ISSUE THREAD

**Issue by SafeWay-2022** [SafeWay-2022/safeway#22]
A search of Points nearby specific location should be added. 
The admin can locate a point in the map and use it as the 'location' for the 'nearby search'.
In addition, filtering options can be set.
The output should be presented as a list, similar to the 'point list', but with all the the fields of the filtering options presented.

API: https://c4u-match-org.appspot.com/docs#/Points%20of%20Interest/get_nearby_needs_poi_nearby_get

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/27/

**Comment by ahik** [comment]
Please check it. 
1. Pagination is missing.
2. Approved, Active and Activated-At not displayed correctly.
3. 'Distance' is a float nomber. Can it have only 3 digits after the dot?
