### ISSUE TITLE
Add 'Loading' spinner 

### ISSUE THREAD

**Issue by SafeWay-2022** [SafeWay-2022/safeway#23]
As there is some delay until the server response to a 'click', a 'loading spinner' should be added. 

The 'loading spinner' should be displayed after the end-user click on a button and until the actual information can be displayed. 

Any spinner that will work can be choose. 
Like: https://loading.io/css/
![Another example](https://user-images.githubusercontent.com/105425162/174437264-3c1330f4-231c-44a0-be3e-2934166d4802.png)

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/43
