### ISSUE TITLE
Warning message before delete

### ISSUE THREAD

**Issue by SafeWay-2022** [SafeWay-2022/safeway#29]
Before actual delete of content, a warning message should be displayed. 

The deletion process should be:
1. User click delete
2. Warning message: "Do you really want to delete this item?" with "Delete" and "Cancel" buttons.
3. Click "Delete" button -> Actual delete request will be send to the backend.
4. Click "Cancel" -> The Message box will be close and *no* delete will be made.

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/41
