### ISSUE TITLE
Authorization - login/logout

### ISSUE THREAD

**Issue by ahik** [SafeWay-2022/safeway#3]
Once AAA mechanism will be ready from the backend, the 'Admin' should have:
1. Login forms. 
2. Logout button.
3. Headers (TBD)

Future:
1. Account managment - Change/forget password.
2. Add new User.

**Comment by ahik** [comment]
The AAA API Is ready: https://c4u-match-org.appspot.com/docs#/AAA
Registration is free to use. 
After succesful [Login](https://c4u-match-org.appspot.com/docs#/AAA/login_for_access_token_aaa_login_post), you will get "OAuth2PasswordBearer" key that should be sent as 'Bearer Header' for all other requests.

**Comment by bfunc** [comment]
> After succesful [Login](https://c4u-match-org.appspot.com/docs#/AAA/login_for_access_token_aaa_login_post), you will get "OAuth2PasswordBearer" key that should be sent as 'Bearer Header' for all other reque

PR created:
https://github.com/SafeWay-2022/safeway/pull/10

Waiting for feedback

**Comment by ahik** [comment]
Merged and auto deployed at: https://safeway-chi.vercel.app/

But someting not working well. 
An admin created:
username: admino01
password: M@k3ItS@f3

It work from the API: https://c4u-match-org.appspot.com/docs#/AAA/login_for_access_token_aaa_login_post
But, on the Admin console it doesn't work.

**Comment by bfunc** [comment]
https://github.com/SafeWay-2022/safeway/pull/11
Merged fix, should be ok now

**Comment by SafeWay-2022** [comment]
Works, thanks.
