### ISSUE TITLE
Nearby - Distance display format

### ISSUE THREAD

**Issue by SafeWay-2022** [SafeWay-2022/safeway#31]
The point list can have 'distance' for each point. 
Distance should be displayed with 3 digit precision. 
Like: **24.974**
and not: 24.97404696603818

@GoodLuckMister 
To get the distances values, the 'add distance' filter should be on.

![Screenshot from 2022-06-21 23-38-08](https://user-images.githubusercontent.com/105425162/174895164-399cba77-53af-4371-986e-8cc499825f58.png)

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/35
