### ISSUE TITLE
Nearby - Skip should starts from 0

### ISSUE THREAD

**Issue by SafeWay-2022** [SafeWay-2022/safeway#32]
The default skip should be zero (0).
If skip=1, the first point will be skipped.

Current request example:
curl 'https://safeway-chi.vercel.app/api/poi/nearby?approved=true&latitude=32.0732655510424&limit=10&skip=1&longitude=34.87060546875001' 

@GoodLuckMister

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/36
