### ISSUE TITLE
Nearby - Approved and Active not displayed

### ISSUE THREAD

**Issue by SafeWay-2022** [SafeWay-2022/safeway#33]
The 'Approved' and the 'Active' boolean values are not shown within the response table. 
@GoodLuckMister 

![Screenshot from 2022-06-22 00-03-54](https://user-images.githubusercontent.com/105425162/174897509-71c52777-c2ce-4dfc-8b77-1338d67c3346.png)

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/37
