### ISSUE TITLE
Nearby - Edit points

### ISSUE THREAD

**Issue by SafeWay-2022** [SafeWay-2022/safeway#34]
Add possibility to edit points that returned from the 'nearby' call. 
Same as in [the 'Points' table](https://safeway-chi.vercel.app/poi).
@GoodLuckMister 

![Screenshot from 2022-06-22 00-12-07](https://user-images.githubusercontent.com/105425162/174898218-0a7f6d3f-741a-4932-b5a6-106d532cfbd0.png)

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/37
