### ISSUE TITLE
Nearby - Boolean search fields should should have possibilty to be ingnored.

### ISSUE THREAD

**Issue by ahik** [SafeWay-2022/safeway#38]
Boolean search fields should have three functionalities:
1. The Boolean options: true or false. 
2. Not set. Where not filter values are sent. In this case items with both 'true' and 'false' should be returend.

Examples: 'Active' and 'Approved'.

At the moment, unset of 'Approved' returns both items. It should returned only 'false' approved items.

![Screenshot from 2022-06-23 12-55-41](https://user-images.githubusercontent.com/3140528/175273787-39716fd7-07a5-4f1c-b7d2-022bfb5a95bc.png)

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/40

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/42

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/48

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/49
