### ISSUE TITLE
[Nearby] Categories and Organizations are not display correctly

### ISSUE THREAD

**Issue by ahik** [SafeWay-2022/safeway#44]
The categories display as one large string and it's hard to understand.

![Screenshot from 2022-06-27 18-10-37](https://user-images.githubusercontent.com/3140528/175974035-27cf2f80-15a8-4f86-990d-8462012ade0f.png)

It should be displayed like in the 'Points' view.

![Screenshot from 2022-06-27 18-13-58](https://user-images.githubusercontent.com/3140528/175974444-a906f5c4-658c-4052-8b37-1bbe980c4ef7.png)

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/46
