### ISSUE TITLE
Map View

### ISSUE THREAD

**Issue by ahik** [SafeWay-2022/safeway#45]
When point are listed, it should have a map-view as an alternative to the tabular view.

For any points selection, the results can be seen as a point in the map or as tabular.
A 'switch view' should be added. 
Click on the 'switch view' from tabular-view, will swich to 'map-view' and display the selected points on the map.
And the way back. In map-view, the 'switch view' display the points back in the regular tabular presentation.

1. The filtering and selection option, should be stay in the top of the view for further selections and filtering.
2. A zoom-out on the map, will add more point. Reminder: the nearby points are returened from the closer one. So 'zoom-out' is like more pages.

![Screenshot from 2022-06-27 18-28-35](https://user-images.githubusercontent.com/3140528/175979601-e6362cf8-0b79-4aa5-bb55-48ee2d5af355.png)

**Comment by GoodLuckMister** [comment]
https://github.com/SafeWay-2022/safeway/pull/47
