### ISSUE TITLE
Boolean fields read/write

### ISSUE THREAD

**Issue by ahik** [SafeWay-2022/safeway#6]
**Describe the bug**
Handling boolean fields ('switch') had two problems:
1. Create/Update always send 'True'. Event if the 'switch' is set to 'false'.
2. Read data always set to 'False'. 

**To Reproduce**
1. Got to POI
2. Add new one with 'active' set as False. -> The data reach the backend api as True

1. Got to POI and set 'active' to 'True'. 
2. The 'switch' is now 'True'
3. Refresh the page
4. The 'switch' will be set to 'false'

1. Read true data. For example the first POI (id: 626448fbc8a6947c6aaf2e18, name: "Művelődési Ház"). 
2. Check this point [in the API](https://c4u-match-org.appspot.com/docs#/Points%20of%20Interest/show_point_of_interest_poi_get__id__get). Enter ID: 626448fbc8a6947c6aaf2e18
3. Check the 'active' value. It's 'true'.
4. Check the same point in [the admin](https://safeway-chi.vercel.app/poi).
5. The 'switch' of the 'active' is set to 'false'.

**Comment by IlyaGershman** [comment]
Pushed fixes, changed the field type to a checkbox

**Comment by ahik** [comment]
Perfect. 
Thanks!
